# Generated by Django 5.2.5 on 2025-08-23 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ["name", "purchase_price"],
                "permissions": [
                    ("can_unpublish_product", "Может отменять публикацию продукта")
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="products",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Указывает, опубликован ли товар на сайте. По умолчанию — не опубликован.",
                verbose_name="Опубликовано",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Продукт пользователя",
            ),
        ),
    ]
